apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-scanner-tunnel.fullname" . }}
  labels:
{{ include "harbor-scanner-tunnel.labels" . | indent 4 }}
type: Opaque
data:
  gitHubToken: {{ .Values.scanner.tunnel.gitHubToken | default "" | b64enc | quote }}
